### ISSUE TITLE
DBI::InterfaceError

### ISSUE THREAD

**Issue by wonderful60** [yteraoka/fluent-plugin-dbi#5]
error_class="DBI::InterfaceError" error="Unable to load driver 'Mysql' (underlying error: uninitialized constant DBI::DBD::Mysql)

**Comment by yteraoka** [comment]
Which version of ruby and fluentd do you using ?

**Comment by wonderful60** [comment]
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]

fluentd-0.12.7

**Comment by yteraoka** [comment]
Unfortunately, dbi gem doesn't work with ruby 1.9 or later.

**Comment by wonderful60** [comment]
Thank you very much to receive your reply.I have already found a new solution-fluent-plugin-mysql-load.

**Comment by gashokkumar040** [comment]
Hi wonderful60,
         i also facing same problem, may i know the solution which u have done for this issue...

error_class="DBI::InterfaceError" error="Unable to load driver 'Mysql' (underlying error: uninitialized constant DBI::DBD::Mysql)

**Comment by yteraoka** [comment]
Hi, @gashokkumar040 What version of Ruby and Fluentd do you use? At my last test, this plugin worked with Ruby 2.3 and Fluentd v0.14 in #6.

**Comment by gashokkumar040** [comment]
Hello, TERAOKA Yoshinori


am using


ruby version

ruby 2.5.1p57


mysql version

mysql  Ver 14.14 Distrib 5.7.21, for osx10.13 (x86_64) using  EditLine
wrapper


On Thu, Apr 12, 2018 at 8:02 PM, TERAOKA Yoshinori <notifications@github.com

**Comment by yteraoka** [comment]
hmm. It seems DBI::DBD::Mysql driver (mysql gem) doesn't work with newer version Ruby. 
Could you use other mysql fluentd plugins? eg. https://github.com/tagomoris/fluent-plugin-mysql
